### ISSUE TITLE
helloflashlight eclipse import

### ISSUE THREAD

**Issue by cyrillemortier** [simpligility/android-maven-plugin#568]
the issue is to make eclipse build the helloflashlight exemple 

my env :

    eclipse luna x64 (on windows 7 x64 pro) set-up with:
    * jdk 1.8.0_25
    * m2e - Maven Integration for Eclipse (1.6.0.20150109-0342)
    * Android for Maven Eclipse (1.2.2.201501131540)
    * the android sdk setup

    the latest Maven installed:
    imported all android jar to my local repo using the simpligility/maven-android-sdk-deployer
    simpligility/android-maven-plugin checkouted on my hard drive (to get the test example) 

The issue occured just after importing a new maven project (helloflashlight: android-maven-plugin/src/test/projects/helloflashlight/) to my workspace :

i can run : mvn clean install android:deploy and it work just fine; i have the project deployed on my mobile.

but what i can't do is debugging with eclipse to put some wait point in my code.

by the way the imported project is not recognized as an android project cause the "manifest" is under "src/main/" and not at the project root folder the "res" folder is also under "src/main".

it that the normal behaviour ?

**Comment by mosabua** [comment]
Should probably file this with https://github.com/rgladwell/m2e-android/issues .. right @rgladwell ?

**Comment by rtack** [comment]
if you import it as existing android code it will successfully import the project as ADT project but will think that the project root is at src/main/ because that's where the manifest file is.

if you import the project as existing maven code the project will have build errors that need to be fixed manually.
1. Run Maven-> Update Project which will fix everything except adding the Android SDK to the classpath. m2e-android seems to rely on project.properties to be present to find the correct android version to use.

Now the error message tells you to change the android properties in the project properties. However that is not possible as it will complain about invalid values. --> You have to manually create a project.properties file or copy one from another project.  
At this stage all the build errors are gone and you can run the project as Android Application. 
You'll also be able again to select whatever android version you want in the eclipse project settings. 


---> it would really help eclipse users if the project.properties file can be added to these projects. That way an import as existing project will go smoothly and no manual steps have to be done at all. 
@mosabua would you accept a patch that adds project.properties files to the test projects?

**Comment by cyrillemortier** [comment]
thank's for the answer, importing the project as a android project solve the issue for the moment.

Now, imagine that i use maven to import some dependencies, how can i debug that kind of project ?
btw not shure that using a "project.properties" would help as this file didn't define the source folder nor the res folder location...

**Comment by WonderCsabo** [comment]
First add a *project.properties* file. Then Import Maven -> Existing Maven projects. That is all.

**Comment by mosabua** [comment]
If someone wants to add a project.properties thats fine by me but I would prefer if it works without.

**Comment by WonderCsabo** [comment]
@mosabua https://github.com/rgladwell/m2e-android/pull/264 :wink:
