### ISSUE TITLE
Support Takari lifecycle

### ISSUE THREAD

**Issue by WonderCsabo** [simpligility/android-maven-plugin#639]
The Takari lifecycle plugin adds its own lifecycle bindings automatically if somebody uses the `takari-jar` packaging. We should also create a packaging for APK and AAR which does the same for Android projects.

**Comment by william-ferguson-au** [comment]
@WonderCsabo @mosabua Can someone explain the Takari lifecycle to me?

**Comment by WonderCsabo** [comment]
Check out thr

**Comment by WonderCsabo** [comment]
Check out the book. http://takari.io/book/40-lifecycle.html

**Comment by mosabua** [comment]
There are two sides to this. The takari-lifecycle plugin enables the build of the android maven plugin to be incremental. Last time I tried this I ran into some annotation processing issues with our usage of the plugin config stuff. This might be fixed. I have to investigate this again.

The more interesting thing is to use the takari lifecycle or just the incremental build support library to get the build of a project using the Android Maven Plugin to become incremental.  This might work by mostly changing out components.xml to use the takari lifecycle plugin instead of the core maven plugins, but that might have far reaching incompatible consequences. The other side is to make the actual goals of the android maven plugin itself to be incremental. That probably lies with using the incremental build support from Takari.

Once I got the docs migrated (currently in progress) and caught up on pull requests and made another release, I can chat to @ifedorenko and @jvanzyl about this in more detail. Maybe we should even make this an topic for an Maven developer hangout.

**Comment by Shusshu** [comment]
I had a good look into the book and tried using it on a java project and also on android project I also feel it could have incompatibilities even if what they are doing is great.

I think the safest approach for the moment is as you said @mosabua we should use the incremental build support from Takari.
It's great there's a lib for that! no need to rebuild the wheel.

We should also keep in mind that the android tools team is working on jack & jill which will replace the javac & dex, for now it's only experimental and lack support for a bunch of things but that might be a better direction and we could use the incremental support from Takariif possible.

**Comment by Shusshu** [comment]
I almost forgot about that Maven dev hangout, yes let us know when and I hope we can get many people in the conversation.

**Comment by WonderCsabo** [comment]
@mosabua this issue is only about replacing core maven plugin goals with Takari ones. Make our goals incremental is #638. Compile the plugin itself with Takari is #532.

**Comment by WonderCsabo** [comment]
BTW where is the incremental lib?

**Comment by mosabua** [comment]
https://github.com/takari/io.takari.incrementalbuild

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
