### ISSUE TITLE
The multi-dex still have some hidden problems

### ISSUE THREAD

**Issue by Cha0sX** [simpligility/android-maven-plugin#699]
Although the plugin support multi-dex. But it's does not work perfectly.

1.In Android Maven Plugin, generate main dex list is not only after compile java step, but also after obfuscate(when we need),  this will cause a problem. Let’s see, this is a part of build process: compile java->obfuscate->dex(within gen main dex list), as we know the classes is changed since obfuscated. It means generate main dex list couldn't base on the origin classes. Obfuscate affects the result of main dex list. So multi-dex may loss some classes what you need/want in main dex.

2.Main dex list generated using shell script(mainDexClasses). The shell script is under build tool directory, and it running base on the specific rules file(mainDexClass.rules) also under build tool directory. So it is inconvenience for every project to add there own rules if necessary, especially for continuous integration, project can not touch the files under build sdk.

These two problems are relate to the correctness and flexibility of multi-dex. I think both are important for production developing. For convenience and verification, I had written another plugin to fix these on my projects first, and now running properly for several versions. But maybe it’s a number of code to add. So I am willing to fix it using my solution, if you may.

The solution:
1.generate main dex list not use shell script, create a new Mojo(MainDexListMojo) instead. Default rules file is under build tool directory and accept param to specific rules file;
2.MainDexListMojo run before ProguardMojo;
3.After ProguardMojo run, retrace class path of main dex list from the mapping file. Make sure main dex list content correct after obfuscated;

**Comment by sballes** [comment]
I have also found two errors/problems when building multidex apks.

**First Problem**
When running script _mainDexClasses.bat_, an execution error ocurred. After a little research I found that tha probable cause to the problem is that the command is not properly built.
I think that the method _generateMainDexClassesFile_ on class _DexMojo.class_ is not working properly on version 4.4.3, so I had to recompile the plugin adding quotes between the input files:
```
StringBuilder sb = new StringBuilder();
sb.append( '"' ).append( StringUtils.join( inputFiles, File.pathSeparatorChar ) ).append( '"' );
commands.add( sb.toString() );
```

**Problem 2**
Now, the call to the script init succesfully but it still returns an error (Windows). I did a little research and I found a valid solution for my problem in [code.google.com.](https://code.google.com/p/android/issues/detail?id=187721&q=-has%3Aowner&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars&start=37100).
I had to modify the script _mainDexClasses.bat_ to delete the quotes in the variable _%disableKeepAnnotated%_ that appears twice at the end of the file.

**Comment by hcoosthuizen** [comment]
I can confirm that this is an issue. Reverting the plugin version to 4.4.2 fixes it, I believe it was broken in this commit: https://github.com/simpligility/android-maven-plugin/commit/24499f20e5d7061e2e686c873f9f4edb8f0f7bd8

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
