### ISSUE TITLE
AAR packaging doesn't seem to create an annotations.zip 

### ISSUE THREAD

**Issue by ronshapiro** [simpligility/android-maven-plugin#746]
According to https://developer.android.com/studio/write/annotations.html, when creating an `.aar` with an `@IntDef` usage, an `annotations.zip` file should be added to the generated artifact so that when it's consumed in another library, those annotations can be understood by Android Studio. 

As far as I can tell (and @netdpb), this plugin doesn't support creating that. (1) Is that the case, and (2) would it be hard to implement if so?

**Comment by mosabua** [comment]
That must be a new "feature" that was added to the aar spec since it was originally created. There might be some support for creating this file as part of the packaging process with the libraries we use as part of the plugin (android sdk tools) but worst case we might have to reverse engineer and implement ourselves.  If you investigate further and maybe even implement we can merge a pull request from you or others.

**Comment by william-ferguson-au** [comment]
Definitely new . That is the only reference I can find to `annotations.zip`

**Comment by ronshapiro** [comment]
Here's the file that I think does this within Gradle: https://android.googlesource.com/platform/tools/base/+/gradle_2.0.0/build-system/gradle-core/src/main/groovy/com/android/build/gradle/internal/LibraryTaskManager.java Does that make any sense to you?

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
